@startuml diagramm_classes







class "<B>Пользователь</B>" as Пользователь {
  + имя_пользователя
  + пароль
  + админ
  + хэш_токена
  
}

class "<B>Категория</B>" as Категория {
  + название
}

class "<B>Товар</B>" as Товар {
  + название
  + **Категория**
}

class "<B>Единица_Измерения</B>" as Единица_Измерения {
    + название
}

class "<B>Купленный_Товар</B>" as Купленный_Товар {
  + **Пользователь**
  + **Товар**
  + количество
  + **Единица_Измерения**
  + цена
  + дата_покупки
}

Пользователь --> Купленный_Товар: добавляет
Товар --> Категория : содержит
Купленный_Товар --> Товар : состоит
Купленный_Товар --> Категория : состоит
Купленный_Товар --> Единица_Измерения : состоит

@enduml
