@startuml use_cases_diagrams


title Регистрация
actor Пользователь

Пользователь -> "Система" : register(username, password)

note left of Пользователь: Описание сценария:

| Шаг | Описание               |
|-----|------------------------|
|  1  | Начало сеанса          |
|  2  | Отправка запроса       |
|  3  | Прием ответа           |
|  4  | Проверка ответа        |
|  5  | Обработка ответа       |
|  6  | Отображение результата |
|  7  | Завершение сеанса      |


@enduml