@startuml add_product

skinparam backgroundColor #FFFFFF

actor User
actor System

User -> System: start
User -> System: addProduct(product_name, category)
System -> User: isCategoryExistsResponse
System -> User: productExistsResponse
System -> User: end

@enduml
