@startuml add_purchased_product

skinparam backgroundColor #FFFFFF


actor User
actor System

User -> System: start
User -> System: addPurchasedProduct(product,count,measurementUnit, price, purchaseDate)
System -> User: isProductExistsResponse
System -> User: isMeasurementUnitExistsResponse
System -> User: end

@enduml
