@startuml delete_measurement_unit

skinparam backgroundColor #FFFFFF


actor User
actor System


User -> System: deleteMeasurementUnit(measurementUnit)
System -> User: deleteMeasurementUnitResponse


@enduml
