@startuml edit_product

skinparam backgroundColor #FFFFFF


actor User
actor System

User -> System: start
User -> System: editProduct(name,category)
System -> User: editProductResponse
System -> User: end

@enduml
