@startuml edit_category

skinparam backgroundColor #FFFFFF


actor User
actor System

User -> System: start
User -> System: editCategory(name)
System -> User: editCategoryResponse
System -> User: end
@enduml
