@startuml edit_purchased_product

skinparam backgroundColor #FFFFFF


actor User
actor System


User -> System: start
User -> System: editPurchasedProduct(product,count,measurementUnit, price, purchaseDate)
System -> User: editPurchasedProductResponse
System -> User: end
@enduml
