@startuml diagram_classes

class Пользователь{
    - номер
    - имя
    - токен
}

class Категория{
    - номер
    - название
}

class Продукт{
    - номер
    - категория
}

class Единица_Измерения{
    - номер
    - название
}

class Купленный_Продукт{
    - номер
    - пользователь
    - продукт
    - количество
    - единица_измерения
    - цена
    - дата_покупки
}

Продукт -- Категория: содержит
Пользователь -- Купленный_Продукт: создает
Купленный_Продукт -- Продукт: состоит
Купленный_Продукт -- Категория: состоит
Купленный_Продукт -- Единица_Измерения: состоит

@enduml